services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3

    ports:
      - "8123:8123"
      - "9000:9000"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/users.d:/etc/clickhouse-server/users.d

    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

  kafka:
    image: apache/kafka:3.7.0

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: "event-analytics-local-01"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest

    ports:
      - "8090:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    depends_on:
      - kafka

  ingestion:
    build: .
    container_name: ingestion
    command: ["event-analytics"]
    env_file: .env
    environment:
      KAFKA_BROKERS: kafka:29092
      INGESTION_BIND: 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  workers:
    build: .
    container_name: workers
    command: ["workers"]
    env_file: .env
    environment:
      KAFKA_BROKERS: kafka:29092
      CLICKHOUSE_URL: http://clickhouse:8123
    depends_on:
      - kafka
      - clickhouse

  analytics:
    build: .
    container_name: analytics
    command: ["analytics"]
    env_file: .env
    environment:
      CLICKHOUSE_URL: http://clickhouse:8123
      ANALYTICS_BIND: 0.0.0.0:8081
    ports:
      - "8081:8081"
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  kafka_data:
